apiVersion: v1
kind: Service
metadata:
  name: captureorderack-svc
  labels:
    app: captureorderack-app
    env: prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: captureorderack-app
